version: '3.8'

services:
  app:
    build: .
    container_name: node-ts-starter-app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - minio
      - maildev
    volumes:
        - .:/usr/src/app

  mongo:
    image: mongo
    container_name: node-ts-starter-mongo
    ports:
      - "${MONGO_CLIENT_PORT}:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: node-ts-starter-redis
    ports:
      - "${REDIS_SERVER_PORT}:6379"

  minio:
    image: minio/minio
    container_name: node-ts-starter-minio
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_API_PORT}:9000" 
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data

  maildev:
    image: maildev/maildev
    container_name: node-ts-starter-maildev
    ports:
      - "${MAILDEV_SMTP}:1025"
      - "${MAILDEV_WEBAPP_PORT}:1080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1080"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo-data:
  minio-data:
